2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Configure stats pid to 1606603
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Loading settings from /home/james/.config/wandb/settings
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Loading settings from /media/james/Projects/GitHub/DATA_340_NLP/Spring_2024/Lecture_Notebooks/wandb/settings
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-03-26 14:11:50,566 INFO    MainThread:1606603 [wandb_init.py:_log_setup():527] Logging user logs to /media/james/Projects/GitHub/DATA_340_NLP/Spring_2024/Lecture_Notebooks/wandb/run-20240326_141150-c9qbtgnl/logs/debug.log
2024-03-26 14:11:50,567 INFO    MainThread:1606603 [wandb_init.py:_log_setup():528] Logging internal logs to /media/james/Projects/GitHub/DATA_340_NLP/Spring_2024/Lecture_Notebooks/wandb/run-20240326_141150-c9qbtgnl/logs/debug-internal.log
2024-03-26 14:11:50,567 INFO    MainThread:1606603 [wandb_init.py:_jupyter_setup():473] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7b25f3f3e440>
2024-03-26 14:11:50,567 INFO    MainThread:1606603 [wandb_init.py:init():567] calling init triggers
2024-03-26 14:11:50,567 INFO    MainThread:1606603 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 128, 'epochs': 10}
2024-03-26 14:11:50,567 INFO    MainThread:1606603 [wandb_init.py:init():592] re-initializing run, found existing run on stack: 9hfrylw4
2024-03-26 14:11:50,568 INFO    MainThread:1606603 [wandb_run.py:_finish():2052] finishing run tucker_labs/mnist-classification/9hfrylw4
2024-03-26 14:11:50,568 INFO    MainThread:1606603 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-03-26 14:11:50,568 INFO    MainThread:1606603 [wandb_run.py:_restore():2275] restore
2024-03-26 14:11:50,568 INFO    MainThread:1606603 [wandb_run.py:_restore():2281] restore done
2024-03-26 14:11:53,290 INFO    MainThread:1606603 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-03-26 14:11:53,290 INFO    MainThread:1606603 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-03-26 14:11:53,292 INFO    MainThread:1606603 [wandb_run.py:_footer_sync_info():3879] logging synced files
2024-03-26 14:11:53,343 INFO    MainThread:1606603 [wandb_init.py:init():617] starting backend
2024-03-26 14:11:53,343 INFO    MainThread:1606603 [wandb_init.py:init():621] setting up manager
2024-03-26 14:11:53,344 INFO    MainThread:1606603 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-26 14:11:53,344 INFO    MainThread:1606603 [wandb_init.py:init():629] backend started and connected
2024-03-26 14:11:53,345 INFO    MainThread:1606603 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-03-26 14:11:53,345 INFO    MainThread:1606603 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-26 14:11:53,346 INFO    MainThread:1606603 [wandb_init.py:init():721] updated telemetry
2024-03-26 14:11:53,350 INFO    MainThread:1606603 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-03-26 14:11:54,478 ERROR   MainThread:1606603 [wandb_init.py:init():780] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-26 14:11:54,541 ERROR   MainThread:1606603 [wandb_init.py:init():1205] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/media/james/Projects/GitHub/DATA_340_NLP/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1187, in init
    run = wi.init()
  File "/media/james/Projects/GitHub/DATA_340_NLP/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 786, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-26 14:13:52,598 INFO    MainThread:1606603 [wandb_settings.py:_apply_login():1941] Applying login settings: {}
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Configure stats pid to 1606603
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Loading settings from /home/james/.config/wandb/settings
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Loading settings from /media/james/Projects/GitHub/DATA_340_NLP/Spring_2024/Lecture_Notebooks/wandb/settings
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-26 14:13:52,601 INFO    MainThread:1606603 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-03-26 14:13:52,602 INFO    MainThread:1606603 [wandb_init.py:_log_setup():527] Logging user logs to /media/james/Projects/GitHub/DATA_340_NLP/Spring_2024/Lecture_Notebooks/wandb/run-20240326_141352-ndenuyhv/logs/debug.log
2024-03-26 14:13:52,602 INFO    MainThread:1606603 [wandb_init.py:_log_setup():528] Logging internal logs to /media/james/Projects/GitHub/DATA_340_NLP/Spring_2024/Lecture_Notebooks/wandb/run-20240326_141352-ndenuyhv/logs/debug-internal.log
2024-03-26 14:13:52,602 INFO    MainThread:1606603 [wandb_init.py:init():567] calling init triggers
2024-03-26 14:13:52,602 INFO    MainThread:1606603 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 128, 'epochs': 10}
2024-03-26 14:13:52,602 INFO    MainThread:1606603 [wandb_init.py:init():617] starting backend
2024-03-26 14:13:52,602 INFO    MainThread:1606603 [wandb_init.py:init():621] setting up manager
2024-03-26 14:13:52,603 INFO    MainThread:1606603 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-26 14:13:52,603 INFO    MainThread:1606603 [wandb_init.py:init():629] backend started and connected
2024-03-26 14:13:52,605 INFO    MainThread:1606603 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-03-26 14:13:52,605 INFO    MainThread:1606603 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-26 14:13:52,605 INFO    MainThread:1606603 [wandb_init.py:init():721] updated telemetry
2024-03-26 14:13:52,610 INFO    MainThread:1606603 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-03-26 14:13:52,789 ERROR   MainThread:1606603 [wandb_init.py:init():780] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-26 14:13:52,839 ERROR   MainThread:1606603 [wandb_init.py:init():1205] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/media/james/Projects/GitHub/DATA_340_NLP/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1187, in init
    run = wi.init()
  File "/media/james/Projects/GitHub/DATA_340_NLP/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 786, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
